require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FixturesController do

  # This should return the minimal set of attributes required to create a valid
  # Fixture. As you add validations to Fixture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "hometeam" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FixturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fixtures as @fixtures" do
      fixture = Fixture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fixtures).should eq([fixture])
    end
  end

  describe "GET show" do
    it "assigns the requested fixture as @fixture" do
      fixture = Fixture.create! valid_attributes
      get :show, {:id => fixture.to_param}, valid_session
      assigns(:fixture).should eq(fixture)
    end
  end

  describe "GET new" do
    it "assigns a new fixture as @fixture" do
      get :new, {}, valid_session
      assigns(:fixture).should be_a_new(Fixture)
    end
  end

  describe "GET edit" do
    it "assigns the requested fixture as @fixture" do
      fixture = Fixture.create! valid_attributes
      get :edit, {:id => fixture.to_param}, valid_session
      assigns(:fixture).should eq(fixture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fixture" do
        expect {
          post :create, {:fixture => valid_attributes}, valid_session
        }.to change(Fixture, :count).by(1)
      end

      it "assigns a newly created fixture as @fixture" do
        post :create, {:fixture => valid_attributes}, valid_session
        assigns(:fixture).should be_a(Fixture)
        assigns(:fixture).should be_persisted
      end

      it "redirects to the created fixture" do
        post :create, {:fixture => valid_attributes}, valid_session
        response.should redirect_to(Fixture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fixture as @fixture" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fixture.any_instance.stub(:save).and_return(false)
        post :create, {:fixture => { "hometeam" => "invalid value" }}, valid_session
        assigns(:fixture).should be_a_new(Fixture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fixture.any_instance.stub(:save).and_return(false)
        post :create, {:fixture => { "hometeam" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fixture" do
        fixture = Fixture.create! valid_attributes
        # Assuming there are no other fixtures in the database, this
        # specifies that the Fixture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fixture.any_instance.should_receive(:update).with({ "hometeam" => "MyString" })
        put :update, {:id => fixture.to_param, :fixture => { "hometeam" => "MyString" }}, valid_session
      end

      it "assigns the requested fixture as @fixture" do
        fixture = Fixture.create! valid_attributes
        put :update, {:id => fixture.to_param, :fixture => valid_attributes}, valid_session
        assigns(:fixture).should eq(fixture)
      end

      it "redirects to the fixture" do
        fixture = Fixture.create! valid_attributes
        put :update, {:id => fixture.to_param, :fixture => valid_attributes}, valid_session
        response.should redirect_to(fixture)
      end
    end

    describe "with invalid params" do
      it "assigns the fixture as @fixture" do
        fixture = Fixture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fixture.any_instance.stub(:save).and_return(false)
        put :update, {:id => fixture.to_param, :fixture => { "hometeam" => "invalid value" }}, valid_session
        assigns(:fixture).should eq(fixture)
      end

      it "re-renders the 'edit' template" do
        fixture = Fixture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fixture.any_instance.stub(:save).and_return(false)
        put :update, {:id => fixture.to_param, :fixture => { "hometeam" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fixture" do
      fixture = Fixture.create! valid_attributes
      expect {
        delete :destroy, {:id => fixture.to_param}, valid_session
      }.to change(Fixture, :count).by(-1)
    end

    it "redirects to the fixtures list" do
      fixture = Fixture.create! valid_attributes
      delete :destroy, {:id => fixture.to_param}, valid_session
      response.should redirect_to(fixtures_url)
    end
  end

end
