require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HomeXisController do

  # This should return the minimal set of attributes required to create a valid
  # HomeXi. As you add validations to HomeXi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HomeXisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all home_xis as @home_xis" do
      home_xi = HomeXi.create! valid_attributes
      get :index, {}, valid_session
      assigns(:home_xis).should eq([home_xi])
    end
  end

  describe "GET show" do
    it "assigns the requested home_xi as @home_xi" do
      home_xi = HomeXi.create! valid_attributes
      get :show, {:id => home_xi.to_param}, valid_session
      assigns(:home_xi).should eq(home_xi)
    end
  end

  describe "GET new" do
    it "assigns a new home_xi as @home_xi" do
      get :new, {}, valid_session
      assigns(:home_xi).should be_a_new(HomeXi)
    end
  end

  describe "GET edit" do
    it "assigns the requested home_xi as @home_xi" do
      home_xi = HomeXi.create! valid_attributes
      get :edit, {:id => home_xi.to_param}, valid_session
      assigns(:home_xi).should eq(home_xi)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HomeXi" do
        expect {
          post :create, {:home_xi => valid_attributes}, valid_session
        }.to change(HomeXi, :count).by(1)
      end

      it "assigns a newly created home_xi as @home_xi" do
        post :create, {:home_xi => valid_attributes}, valid_session
        assigns(:home_xi).should be_a(HomeXi)
        assigns(:home_xi).should be_persisted
      end

      it "redirects to the created home_xi" do
        post :create, {:home_xi => valid_attributes}, valid_session
        response.should redirect_to(HomeXi.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved home_xi as @home_xi" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeXi.any_instance.stub(:save).and_return(false)
        post :create, {:home_xi => { "name" => "invalid value" }}, valid_session
        assigns(:home_xi).should be_a_new(HomeXi)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeXi.any_instance.stub(:save).and_return(false)
        post :create, {:home_xi => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested home_xi" do
        home_xi = HomeXi.create! valid_attributes
        # Assuming there are no other home_xis in the database, this
        # specifies that the HomeXi created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HomeXi.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => home_xi.to_param, :home_xi => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested home_xi as @home_xi" do
        home_xi = HomeXi.create! valid_attributes
        put :update, {:id => home_xi.to_param, :home_xi => valid_attributes}, valid_session
        assigns(:home_xi).should eq(home_xi)
      end

      it "redirects to the home_xi" do
        home_xi = HomeXi.create! valid_attributes
        put :update, {:id => home_xi.to_param, :home_xi => valid_attributes}, valid_session
        response.should redirect_to(home_xi)
      end
    end

    describe "with invalid params" do
      it "assigns the home_xi as @home_xi" do
        home_xi = HomeXi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeXi.any_instance.stub(:save).and_return(false)
        put :update, {:id => home_xi.to_param, :home_xi => { "name" => "invalid value" }}, valid_session
        assigns(:home_xi).should eq(home_xi)
      end

      it "re-renders the 'edit' template" do
        home_xi = HomeXi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeXi.any_instance.stub(:save).and_return(false)
        put :update, {:id => home_xi.to_param, :home_xi => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested home_xi" do
      home_xi = HomeXi.create! valid_attributes
      expect {
        delete :destroy, {:id => home_xi.to_param}, valid_session
      }.to change(HomeXi, :count).by(-1)
    end

    it "redirects to the home_xis list" do
      home_xi = HomeXi.create! valid_attributes
      delete :destroy, {:id => home_xi.to_param}, valid_session
      response.should redirect_to(home_xis_url)
    end
  end

end
